version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    ports:
      - "5044:5044"